
[gcloud]
disabled = true

[python]
detect_files = ['.python-version', 'Pipfile', '__init__.py','requirements.txt', 'setup.py']
# python_binary = [
#   "python",
#   ".pixi/envs/default/bin/python",
# ]
